### ISSUE TITLE
shake is different in other scene at same frame, or even on other computers rendering the file too.

### ISSUE THREAD

**Issue by loicbramoulle** [EatTheFuture/camera_shakify#17] opened 2023-03-07 22:50 UTC
Blender 3.4 (or any)
The shake is different when changing scene (or even computer ?)
if you have your camera in two scenes, and swap between these scenes at the same frame, you can see that the camera is not aligned with itself in other scenes.
I always had issue when rendering, and the only way to use the addon is currently to object>animation>bake action on a duplicated version of the camera, where you remove the shakify (that don't get cleared by the remove constraints)
![image](https://user-images.githubusercontent.com/49880198/223571822-82481fe2-a899-46c4-a531-1c184d588e3a.png)

**Comment by cessen** [comment] 2023-03-13 00:54
Thanks for reporting this!  I'm currently on vacation until April, so I won't be able to get to this before then.  But I'll try to get to it not too long after that.

**Comment by loicbramoulle** [comment] 2023-03-13 01:03
Thanks a lot ! damn, holidays, haven't heard that in a while, enjoy !
for anyone with this unconsistency issue, baking action on a duplicated camera works really well and it's superfast, to export the camera to after effects or anything, and you'll be sure all your passes will have the same shake cam.

**Comment by cessen** [comment] 2023-04-09 17:06
Just dropping a note that this is still on my radar.  I'm back from vacation, but am busy with some other stuff at the moment.  But if this is urgent, please let me know and I'll bump up its priority.

**Comment by loicbramoulle** [comment] 2023-04-09 20:03
No rush at all, thanks a lot !

**Comment by michaelquigley** [comment] 2023-04-26 00:49
Also ran into this same issue in a multi-machine rendering situation.

**Comment by cessen** [comment] 2023-05-03 12:52
@loicbramoulle 

I was able to reproduce the issue when linking the same camera across multiple scenes (the camera simply doesn't shake in all but one scene, which I assume is what you were running into as well?).  That is now fixed in master.  If you could test it to confirm the fix, I'd really appreciate it!

I'm not sure about the issue where the shake is different across different machines.  Can you provide more details about the situation(s) where that's happening?  @michaelquigley too.  For example, is it a render farm situation?  Is it a commercial render farm, or one that you control?  How are the frames split up between the machines (if you know)?  Have you confirmed they all have Camera Shakify installed?  The same version of Camera Shakify?  And (importantly) does the fix I just made for the cross-scene linking issue also fix the cross-machine issue, or not?

**Comment by cessen** [comment] 2023-05-03 16:41
> if it's necessary to have it installed on all of the machines in the farm, I can do that and re-test.

Camera Shakify does need to be installed for the camera shakes to work.  So indeed, you'll need to bake the camera animation if you want to render on machines without it installed.

**Comment by cessen** [comment] 2023-11-03 20:37
@loicbramoulle Did you get a chance to re-test with latest master?

@michaelquigley Did you get a chance to test after installing Camera Shakify on the render machines?

**Comment by loicbramoulle** [comment] 2023-11-04 22:13
Hi Nathan, yes I can confirm it now works on multiple scenes !
Thanks tons !

**Comment by cessen** [comment] 2023-11-05 11:18
Okay, great!  I'll close this issue, then, since that was the reported problem.

@michaelquigley If you have any remaining problems after installing Camera Shakify on your render machines, please feel free to open new issues for them.

**Closed by cessen** 2023-11-05 11:18 UTC
