### ISSUE TITLE
Install not working on Blender 3.0.0

### ISSUE THREAD

**Issue by theghostronaut** [EatTheFuture/camera_shakify#4] opened 2022-01-05 16:27 UTC
I'm on Blender 3.0.0 (Windows) and I'm not able to install the addon.
I've tried adding it through Add-ons > Install, but the addon doesn't show up.
Does the plugin not yet work in this version of Blender?

**Comment by cessen** [comment] 2022-01-05 20:46
I just tested on my own system, and it seems to work fine.

Can you describe the exact steps (including e.g. how you're downloading the addon) that you're taking to install the addon?

**Comment by cessen** [comment] 2022-02-01 03:17
It's been several weeks since the report, and the needed information has not yet been provided by the reporter, so I'm closing this.

However, if this is indeed an actual problem with Camera Shakify, I definitely want to track it down.  So if anyone else encounters this problem, please do open another issue, and please describe the exact installation steps you took (so that I can hopefully reproduce it).

**Closed by cessen** 2022-02-01 03:17 UTC

**Comment by theghostronaut** [comment] 2022-02-01 16:21
Please excuse my lack of response. The issue was with me, I misunderstood how to install the addon and didn't use the entire zip.

**Comment by cessen** [comment] 2022-02-01 21:15
No worries!  Thanks for getting back to us!
