### ISSUE TITLE
Installs but doesn't work on Blender 4.3.0 (Alpha)

### ISSUE THREAD

**Issue by PKMpl** [EatTheFuture/camera_shakify#28] opened 2024-05-30 07:57 UTC
**Blender 4.2.0 (Alpha) Ubuntu 24.04**

**Bug**
Camera Shakify can be installed as a legacy addon. It appears in the settings, but doesn't add any shake to the camera no matter the settings. It worked on the previous Alpha version of Blender.

**To Reproduce**
1. Install Blender 4.2.0 (Bug doesn't happen in the stable version 4.1.0)
2. Install Shakify (only allowed as legacy install)
3. Try to add shake, no impact on camera

**Expected behavior**
Camera moves after clicking adding shake item

![image](https://github.com/EatTheFuture/camera_shakify/assets/3823196/cf9fb3f2-5bf6-4e38-8899-d8cf06232625)

**Comment by Vinfinity-Gaming** [comment] 2024-06-04 03:15
for me, i just get spit an error when i try to install it

**Comment by Vinfinity-Gaming** [comment] 2024-06-05 18:46
> for me, i just get spit an error when i try to install it

nvm, it still installs now but it still has the issue of doing nothing

**Comment by ra100** [comment] 2024-06-14 19:47
Same with 4.3 Alpha.

**Comment by ra100** [comment] 2024-06-16 22:22
@PKMpl @Vinfinity-Gaming can you try downloading and installing this verion? https://github.com/ra100/camera_shakify
I've tried to fix it and looks working.

**Comment by cessen** [comment] 2024-06-23 18:05
Sorry it's taken me so long to respond on this.  I'll take a look the next chance I get.  And thanks for the PR @ra100 !

**Comment by ra100** [comment] 2024-06-23 20:17
Seems it's working fine in 4.2.0 Beta.
And the what I thought was a fix, doesn't work on 4.3.0 Alpha, I guess, we wait for more stable version of Blender 4.3 :)

**Comment by JayTheCoderX** [comment] 2024-07-05 05:14
It doesn't work on the latest 4.3 alpha nightly build still

**Comment by cessen** [comment] 2024-07-08 06:51
@JayTheCoderX Thanks for letting me know!  I've done a bit of preliminary investigation, and it looks like it *might* be a regression in Blender.  I'll make sure that whatever needs fixing (whether that be in Blender or Camera Shakify) gets fixed.

**Comment by marklio** [comment] 2024-08-03 16:36
@cessen Is there a current known workaround on this? Known working Blender version? Maybe a Blender bug to follow?

**Comment by cessen** [comment] 2024-08-04 08:32
It should be working in the latest Blender release (4.2).  If that's not the case, please let me know since that's a lot more urgent.

I'm not aware of any workarounds for Blender 4.3 alpha, but the actual 4.3 release is still a ways off, so I haven't been prioritizing fixing it yet.  If you're using 4.3 alpha for production for some reason, let me know and I'll up the priority.

**Comment by marklio** [comment] 2024-08-05 22:19
@cessen Looks like 4.2.1 RC can do everything I need for my project, and Shakify seems to work fine there, so that should work as a workaround. I tend to do lots of prototype stuff on latest, and sometimes those turn into "more real" projects, so I tend to just stay there.

**Comment by cessen** [comment] 2024-09-22 10:47
I've done some investigation, and it seems to be a bug in Blender.  I've made a report here: https://projects.blender.org/blender/blender/issues/127976

**Comment by PKMpl** [comment] 2024-09-23 19:23
It actually started working again some time after that. Not sure why, maybe there was some minor update to Blender I didn't notice

**Comment by cessen** [comment] 2024-09-23 19:51
@PKMpl Do you mean on Blender 4.2.x?  This issue is now about Blender 4.3 alpha (soon to be beta), which when I checked yesterday was still broken.

(I suspect I know why--it has to do with some experimental features that are enabled in the alpha builds, but disabled in the final release. So likely it would fix itself on release of 4.3 anyway, and that's likely why 4.2 magically was fixed on release as well.  But the issue should get fixed properly regardless, since eventually those Blender features will become non-experimental.)

**Comment by cessen** [comment] 2024-09-25 06:17
The bug has been fixed in Blender, and I've confirmed that Camera Shakify works again with the fix.

**Closed by cessen** 2024-09-25 06:17 UTC
